server:
  port: 3011
  servlet:
    contextPath: /api/xenia
    getResponse: /campaign/response


spring:
  data:
    mongodb:
#      uri: mongodb+srv://user1:user1234@xenia.jdzwovi.mongodb.net/phaseTwoDatabase2?retryWrites=true&w=majority&ssl=true
      uri: mongodb://localhost:27017/d6nrule?authSource=admin
      auto-index-creation: true
  application:
    name: XENIA-SERVICE


# GET http://localhost:3011/api/xenia/d6n/campaign/campaign/response